---
name: ci/cd

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: write
  issues: write
  packages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

on:
  pull_request: {}
  push:
    branches:
    - master
    - bump-version-*
    tags:
    - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-
    - run: make lint
    - run: make test

  build-and-push-alpha:
    if: startsWith(github.ref, 'refs/heads/bump-version-')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get alpha version from branch name
      id: get_alpha_version
      run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/heads\/bump-version-/v}"

    - name: Build and push alpha image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.multistage
        target: container-agent
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: |
          mackerel/mackerel-container-agent:${{ steps.get_alpha_version.outputs.VERSION }}-alpha

    - name: Build and push alpha image with plugins
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.multistage
        target: container-agent-with-plugins
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: |
          mackerel/mackerel-container-agent:${{ steps.get_alpha_version.outputs.VERSION }}-plugins-alpha

  build-and-push-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get version from tag
      id: get_version
      run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"

    - name: Build and push release image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.multistage
        target: container-agent
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: |
          mackerel/mackerel-container-agent:latest
          mackerel/mackerel-container-agent:${{ steps.get_version.outputs.VERSION }}

    - name: Build and push release image with plugins
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.multistage
        target: container-agent-with-plugins
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: |
          mackerel/mackerel-container-agent:plugins
          mackerel/mackerel-container-agent:${{ steps.get_version.outputs.VERSION }}-plugins

