---
name: ci

on:
  workflow_dispatch:
  pull_request: {}
  push:
    branches:
    - master
#   tags:
#   - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-
    - run: make lint
    - run: make test

  build-and-push:
    # if: startsWith(github.ref, 'refs/heads/bump-version-') || startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    # - uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get a Bump Version Name from branch name
      # if: startsWith(github.ref, 'refs/heads/bump-version-')
      id: get_alpha_version
      # run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/heads\/bump-version-/v}"
      run: echo "::set-output name=VERSION::rehearsal"

    - name: Build Alpha
      # if: startsWith(github.ref, 'refs/heads/bump-version-')
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.multistage
        target: container-agent
        platforms: |
          linux/amd64
          linux/arm64
        # push: true
        tags: |
          mackerel/mackerel-container-agent:${{ steps.get_alpha_version.outputs.VERSION }}-alpha

    - name: Build Alpha with plugins
      # if: startsWith(github.ref, 'refs/heads/bump-version-')
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.multistage
        target: container-agent-with-plugins
        platforms: |
          linux/amd64
          linux/arm64
        # push: true
        tags: |
          mackerel/mackerel-container-agent:${{ steps.get_alpha_version.outputs.VERSION }}-plugins-alpha

#   - name: Get a Version Name from tag
#     if: startsWith(github.ref, 'refs/tags/v')
#     id: get_version
#     run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"

#   - name: Build Release
#     if: startsWith(github.ref, 'refs/tags/v')
#     uses: docker/build-push-action@v2
#     with:
#       context: .
#       file: Dockerfile.multistage
#       target: container-agent
#       platforms: |
#         linux/amd64
#         linux/arm64
#       push: true
#       tags: |
#         mackerel/mackerel-container-agent:latest
#         mackerel/mackerel-container-agent:${{ steps.get_version.outputs.VERSION }}

#   - name: Build Release with plugins
#     if: startsWith(github.ref, 'refs/tags/v')
#     uses: docker/build-push-action@v2
#     with:
#       context: .
#       file: Dockerfile.multistage
#       target: container-agent-with-plugins
#       platforms: |
#         linux/amd64
#         linux/arm64
#       push: true
#       tags: |
#         mackerel/mackerel-container-agent:plugins
#         mackerel/mackerel-container-agent:${{ steps.get_version.outputs.VERSION }}-plugins

